export const TIRE_ID = {
  RL: 0,
  RR: 1,
  FL: 2,
  FR: 3
};

export enum TireId {
  RL,
  RR,
  FL,
  FR
}

export const TEAM_TYPES = {
  0: 'Mercedes',
  1: 'Ferrari',
  2: 'Red Bull Racing',
  3: 'Williams',
  4: 'Racing Point',
  5: 'Renault ',
  6: 'Alpha Tauri',
  7: 'Haas',
  8: 'McLaren',
  9: 'Alfa Romeo'
};

export const TRACK_TYPES = {
  '-1': 'Unknown',
  0: 'Melbourne',
  1: 'Paul Ricard',
  2: 'Shanghai',
  3: 'Sakhir (Bahrain)',
  4: 'Catalunya',
  5: 'Monaco',
  6: 'Montreal',
  7: 'Silverstone',
  8: 'Hockenheim',
  9: 'Hungaroring',
  10: 'Spa',
  11: 'Monza',
  12: 'Singapore',
  13: 'Suzuka',
  14: 'Abu Dhabi',
  15: 'Texas',
  16: 'Brazil',
  17: 'Austria',
  18: 'Sochi',
  19: 'Mexico',
  20: 'Baku (Azerbaijan)',
  21: 'Sakhir Short',
  22: 'Silverstone Short',
  23: 'Texas Short',
  24: 'Suzuka Short',
  25: 'Hanoi',
  26: 'Zandvoort',
};

export const NATIONALITY_TYPES = {
  0: '',
  1: '',
  2: '',
  3: '',
  4: '',
  5: '',
  6: '',
  7: '',
  8: '',
  9: '',
  10: '',
  11: '',
  12: '',
  13: '',
  14: '',
  15: '',
  16: '',
  17: '',
  18: '',
  19: '',
  20: '',
  21: '',
  22: '',
  23: '',
  24: '',
  25: '',
  26: '',
  27: '',
  28: '',
  29: '',
  30: '',
  31: '',
  32: '',
  33: '',
  34: '',
  35: '',
  36: '',
  37: '',
  38: '',
  39: '',
  40: '',
  41: '',
  42: '',
  43: '',
  44: '',
  45: '',
  46: '',
  47: '',
  48: '',
  49: '',
  50: '',
  51: '',
  52: '',
  53: '',
  54: '',
  55: '',
  56: '',
  57: '',
  58: '',
  59: '',
  60: '',
  61: '',
  62: '',
  63: '',
  64: '',
  65: '',
  66: '',
  67: '',
  68: '',
  69: '',
  70: '',
  71: '',
  72: '',
  73: '',
  74: '',
  75: '',
  76: '',
  77: '',
  78: '',
  79: '',
  80: '',
  81: '',
  82: '',
  83: '',
  84: '',
  85: '',
  86: '',
  87: '',
  88: ''
};

export const SURFACE_TYPES = {
  0: 'Tarmac',
  1: 'Rumble strip',
  2: 'Concrete',
  3: 'Rock',
  4: 'Gravel',
  5: 'Mud',
  6: 'Sand',
  7: 'Grass',
  8: 'Water',
  9: 'Cobblestone',
  10: 'Metal',
  11: 'Ridged'
};

export const PENALTY_TYPES = {
  0: 'Drive through',
  1: 'Stop Go',
  2: 'Grid penalty',
  3: 'Penalty reminder',
  4: 'Time penalty',
  5: 'Warning',
  6: 'Disqualified',
  7: 'Removed from formation lap',
  8: 'Parked too long timer',
  9: 'Tyre regulations',
  10: 'This lap invalidated',
  11: 'This and next lap invalidated',
  12: 'This lap invalidated without reason',
  13: 'This and next lap invalidated without reason',
  14: 'This and previous lap invalidated',
  15: 'This and previous lap invalidated without reason',
  16: 'Retired',
  17: 'Black flag timer'
};

export const INFRINGEMENT_TYPES = {
  0: 'Blocking by slow driving',
  1: 'Blocking by wrong way driving',
  2: 'Reversing off the start line',
  3: 'Big Collision',
  4: 'Small Collision',
  5: 'Collision failed to hand back position single',
  6: 'Collision failed to hand back position multiple',
  7: 'Corner cutting gained time',
  8: 'Corner cutting overtake single',
  9: 'Corner cutting overtake multiple',
  10: 'Crossed pit exit lane',
  11: 'Ignoring blue flags',
  12: 'Ignoring yellow flags',
  13: 'Ignoring drive through',
  14: 'Too many drive throughs',
  15: 'Drive through reminder serve within n laps',
  16: 'Drive through reminder serve this lap',
  17: 'Pit lane speeding',
  18: 'Parked for too long',
  19: 'Ignoring tyre regulations',
  20: 'Too many penalties',
  21: 'Multiple warnings',
  22: 'Approaching disqualification',
  23: 'Tyre regulations select single',
  24: 'Tyre regulations select multiple',
  25: 'Lap invalidated corner cutting',
  26: 'Lap invalidated running wide',
  27: 'Corner cutting ran wide gained time minor',
  28: 'Corner cutting ran wide gained time significant',
  29: 'Corner cutting ran wide gained time extreme',
  30: 'Lap invalidated wall riding',
  31: 'Lap invalidated flashback used',
  32: 'Lap invalidated reset to track',
  33: 'Blocking the pitlane',
  34: 'Jump start',
  35: 'Safety car to car collision',
  36: 'Safety car illegal overtake',
  37: 'Safety car exceeding allowed pace',
  38: 'Virtual safety car exceeding allowed pace',
  39: 'Formation lap below allowed speed',
  40: 'Retired mechanical failure',
  41: 'Retired terminally damaged',
  42: 'Safety car falling too far back',
  43: 'Black flag timer',
  44: 'Unserved stop go penalty',
  45: 'Unserved drive through penalty',
  46: 'Engine component change',
  47: 'Gearbox change',
  48: 'League grid penalty',
  49: 'Retry penalty',
  50: 'Illegal time gain',
  51: 'Mandatory pitstop'
};

export const ZONE_FLAG_TYPES = {
  '-1': 'Unknown',
  0: 'None',
  1: 'Green',
  2: 'Blue',
  3: 'Yellow',
  4: 'Red'
};

export const SESSION_TYPES = {
  0: 'Unknown',
  1: 'Practice 1',
  2: 'Practice 2',
  3: 'Practice 3',
  4: 'Short Practice',
  5: 'Qualification 1',
  6: 'Qualification 2',
  7: 'Qualification 3',
  8: 'Short Qualification',
  9: 'OSQ',
  10: 'Race',
  11: 'Race 2',
};

export const WEATHER_TYPES = {
  0: 'Clear',
  1: 'Light cloud',
  2: 'Overcast',
  3: 'Light rain',
  4: 'heavy rain',
  5: 'Storm'
};

export const SAFETY_CAR_STATUS_TYPES = {
  0: 'No safety car',
  1: 'Full safety car',
  2: 'Virtual safety car',
};

export const PIT_STATUS_TYPES = {
  0: 'None',
  1: 'Pitting',
  2: 'In pit area'
};

export const DRIVER_STATUS_TYPES = {
  0: 'In garage',
  1: 'Flying lap',
  2: 'In lap',
  3: 'Out lap',
  4: 'On track',
};

export const RESULT_STATUS_TYPES = {
  0: 'Invalid',
  1: 'Inactive',
  2: 'Active',
  3: 'Finished',
  4: 'Disqualified',
  5: 'Not classified',
  6: 'Retired'
};
